# This file was generated by GoReleaser. DO NOT EDIT.
cask "checksy" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "47267155cad82c1da93832e9cf1a8633c8a9ec099917efb62e08c1bbb8310566"
      url "https://github.com/flexdinesh/checksy/releases/download/v#{version}/checksy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a78921da2906a7aaf2e06a4f24efe2a2449860d03843f6e878e5e0b02beb866"
      url "https://github.com/flexdinesh/checksy/releases/download/v#{version}/checksy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fc41176e1aee0fd0f10834051f0b0de406c9a83adfd429f472166c4962428b2e"
      url "https://github.com/flexdinesh/checksy/releases/download/v#{version}/checksy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "348f4ce54ee9caf64af0bfb31dcf3617990385c37c6138e71eb858c4b6d784c7"
      url "https://github.com/flexdinesh/checksy/releases/download/v#{version}/checksy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "checksy"
  desc "Internet connectivity checker with HTTP, ping, DNS, and IP diagnostics"
  homepage "https://github.com/flexdinesh/checksy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "checksy"

  # No zap stanza required

  caveats <<~EOS
    Run `checksy --help` to view available command-line options.
  EOS
end
