# This file was generated by GoReleaser. DO NOT EDIT.
cask "checksy" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "6302742d5f6479e068c15dcf58c50b7f9afed499d8198a5008582be8c6d3329d"
      url "https://github.com/flexdinesh/checksy/releases/download/v#{version}/checksy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a2b532ecbbf4b305625269812bca787d8951987c10697390cebde80c411149cf"
      url "https://github.com/flexdinesh/checksy/releases/download/v#{version}/checksy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "89fb8eaad0cbfcf95c6ce18012284d1fa2aa465018ebb63217aae57ef098a220"
      url "https://github.com/flexdinesh/checksy/releases/download/v#{version}/checksy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "785663c63bac2360ac9a59285d0bc322f77b809233431f6fee2b4b91afa119de"
      url "https://github.com/flexdinesh/checksy/releases/download/v#{version}/checksy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "checksy"
  desc "Internet connectivity checker with HTTP, ping, DNS, and IP diagnostics"
  homepage "https://github.com/flexdinesh/checksy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "checksy"

  # No zap stanza required

  caveats <<~EOS
    Run `checksy --help` to view available command-line options.
  EOS
end
