# This file was generated by GoReleaser. DO NOT EDIT.
cask "checksy" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "72b1cfd4c23569bddba48a7b0bd7addf39ed53e4855ef0974d73b959acd01fb0"
      url "https://github.com/flexdinesh/checksy/releases/download/v#{version}/checksy_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/flexdinesh/checksy/"
    end
    on_arm do
      sha256 "594bba0028a7f701afa7847ebdf7d1d4fe04405a1494d8eb38d37cea584d5875"
      url "https://github.com/flexdinesh/checksy/releases/download/v#{version}/checksy_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/flexdinesh/checksy/"
    end
  end

  on_linux do
    on_intel do
      sha256 "84fa34339c6f733a12beba266026d968a974d444dad1951c7ffb9bb4951d3552"
      url "https://github.com/flexdinesh/checksy/releases/download/v#{version}/checksy_#{version}_linux_amd64.tar.gz",
        verified: "github.com/flexdinesh/checksy/"
    end
    on_arm do
      sha256 "02baf0883126e162a70e15fb836419f1f7e1308cf4905da8f8dd9a08320767da"
      url "https://github.com/flexdinesh/checksy/releases/download/v#{version}/checksy_#{version}_linux_arm64.tar.gz",
        verified: "github.com/flexdinesh/checksy/"
    end
  end

  name "checksy"
  desc "Internet connectivity checker with HTTP, ping, DNS, and IP diagnostics"
  homepage "https://github.com/flexdinesh/checksy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "checksy"

  # No zap stanza required

end
