# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-drop" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "166da87c8e493137dc8c329e056ccdba9b31ab96841a204fbd0ceca000c75c6c"
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v#{version}/ssh-drop_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea9311b50fe0868d7f43ed7a89ee0f1c6b77a979625ce089345a6e38af44ac62"
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v#{version}/ssh-drop_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c79db2082e57beec1680e7a94f29df40ab83a1d76709dbbe4de458cf9f69b4d2"
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v#{version}/ssh-drop_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "072e6dc1d3c57875dad13caf1c47c74531db9255b22cffee6ab982c188429f87"
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v#{version}/ssh-drop_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ssh-drop"
  desc "Interactive CLI for dropping local files onto SSH remotes with rsync"
  homepage "https://github.com/flexdinesh/ssh-drop"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "rsync",
    ]

  binary "ssh-drop"

  # No zap stanza required

  caveats <<~EOS
    Run `ssh-drop --help` to view available command-line options.
  EOS
end
