# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-drop" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "d1c1c5780cdd891bc54f7be5ba1212ec101ea37be48689e573ac2fd5812b0f3e"
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v#{version}/ssh-drop_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4772b8f4ecce82fb8daa30e76f88efc7ea8f2afe9e6c6dd525efc31ac0c49f47"
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v#{version}/ssh-drop_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2cfbaadf82226a3ca395ce6efdde691508e8b488e67f8efbb9216bbaac8fe97d"
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v#{version}/ssh-drop_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d104b4c9e6e02d97d2e9b9ca93d5cb2b517e472a44a2c03b4890cb3724d5bec5"
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v#{version}/ssh-drop_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ssh-drop"
  desc "Interactive CLI for dropping local files onto SSH remotes with rsync"
  homepage "https://github.com/flexdinesh/ssh-drop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-drop"

  # No zap stanza required

  caveats <<~EOS
    ssh-drop requires rsync in your PATH for transfers.
    Install it with `brew install rsync` if your system does not provide it.
    Run `ssh-drop --help` to view available command-line options.
  EOS
end
