# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-drop" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "af7a114d4227f2db3e7da3a9dda108f5c9700f53fadddad27a05af6697248f42"
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v#{version}/ssh-drop_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "777e8d6f2c2f6d89f27b9cd25001c4b30f3946a6b74e0acd4b49079172cf07f6"
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v#{version}/ssh-drop_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "96148f2104d6d0789d01d2ee70e1dfd64b0cb2748effcc1f7e647b61ee486b9e"
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v#{version}/ssh-drop_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fbcfa12a14f95d26923b16daed59532cfc1c1601d33445b42337c336de8366a7"
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v#{version}/ssh-drop_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ssh-drop"
  desc "Interactive CLI for dropping local files onto SSH remotes with rsync"
  homepage "https://github.com/flexdinesh/ssh-drop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-drop"

  # No zap stanza required

  caveats <<~EOS
    ssh-drop requires rsync in your PATH for transfers.
    Install it with `brew install rsync` if your system does not provide it.
    Run `ssh-drop --help` to view available command-line options.
  EOS
end
