# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Checksy < Formula
  desc "Internet connectivity checker with HTTP, ping, DNS, and IP diagnostics"
  homepage "https://github.com/flexdinesh/checksy"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flexdinesh/checksy/releases/download/v0.1.1/checksy_0.1.1_darwin_amd64.tar.gz"
      sha256 "e1f96b89b52875487bc0ee2d7e08e32fb0cfd5067e799d30b81cef686f8f1749"

      def install
        bin.install "checksy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flexdinesh/checksy/releases/download/v0.1.1/checksy_0.1.1_darwin_arm64.tar.gz"
      sha256 "36f6109aabb284e07f9b22f6d166f9875324fa7a5cff388aebfb9e232f118ac6"

      def install
        bin.install "checksy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/flexdinesh/checksy/releases/download/v0.1.1/checksy_0.1.1_linux_amd64.tar.gz"
      sha256 "729709cea4407e5bf96f825e4ea63cdd11a3842952f32e1197e5c24c0895c9f8"
      def install
        bin.install "checksy"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/flexdinesh/checksy/releases/download/v0.1.1/checksy_0.1.1_linux_arm64.tar.gz"
      sha256 "55f64febf54c34d2016dfd3b588dee6926726f0e956e043e46f48a75d2c38d6b"
      def install
        bin.install "checksy"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/checksy --version")
  end
end
