# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshDrop < Formula
  desc "Interactive CLI for dropping local files onto SSH remotes with rsync"
  homepage "https://github.com/flexdinesh/ssh-drop"
  version "0.1.1"

  depends_on "rsync"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v0.1.1/ssh-drop_0.1.1_darwin_amd64.tar.gz"
      sha256 "fb1842f361663e5de1ffa8a3bd7f297a840f8264dcf7e6d05ebc8f85a4ed69d2"

      def install
        bin.install "ssh-drop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v0.1.1/ssh-drop_0.1.1_darwin_arm64.tar.gz"
      sha256 "fd37c57251e4c82e56fa580c43f3360e75492563a6982718842b1c000147ec83"

      def install
        bin.install "ssh-drop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v0.1.1/ssh-drop_0.1.1_linux_amd64.tar.gz"
      sha256 "c48302eb0aff8017c705752f2e747cd9211ade4ece2df399006acea1e09ccec2"
      def install
        bin.install "ssh-drop"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/flexdinesh/ssh-drop/releases/download/v0.1.1/ssh-drop_0.1.1_linux_arm64.tar.gz"
      sha256 "2d2e9ca941f1a94fb7bdb238409a2c17c272278ed20bd11b117321086d797a3c"
      def install
        bin.install "ssh-drop"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ssh-drop --version")
  end
end
